Troubleshoot

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -85,59 +85,63 @@ runs:
         triggers: ${{ inputs.triggers }}
         diff_branch: ${{ inputs.diff_branch }}
 
-    # Setup Java and cache dir
-    - uses: actions/setup-java@v4
-      with:
-        cache: ${{ inputs.java-cache }}
-        distribution: ${{ inputs.java-distribution }}
-        java-version: ${{ inputs.java-version }}
-        server-id: 'github'
-
-    # Run tests, hopefully generating coverage for SonarCloud
-    - name: Run Tests
-      if: steps.diff.outputs.triggered == 'true'
-      shell: bash
-      run: |
-        # Run tests
-        cd ${{ inputs.dir }}
-        ${{ inputs.commands }}
-
-    ### Optional SonarCloud
-
-    - if: inputs.sonar_token && steps.diff.outputs.triggered == 'true'
-      env:
-        SONAR_TOKEN: ${{ inputs.sonar_token }}
-      shell: bash
-      run: |
-        # Run SonarCloud for ${{ inputs.java-cache }}
-
-        if [ "${{ inputs.java-cache }}" == "maven" ]; then
-          SONAR_CMD="mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar"
-        elif [ "${{ inputs.java-cache }}" == "gradle" ]; then
-          SONAR_CMD="./gradlew build sonarqube --info"
-        else
-          echo "ERROR: inputs.java-cache = ${{ inputs.java-cache }}"
-          exit 1
-        fi
-
-        cd ${{ inputs.dir }}
-        "${SONAR_CMD}" -Dsonar.host.url=https://sonarcloud.io ${{ inputs.sonar_args }}
-
-    ### Cleanup
-
-    # Fix - Docker can take file ownership, causing a cleanup fail
     - shell: bash
-      if: steps.diff.outputs.triggered == 'true'
-      id: get_uid
       run: |
-        # User for workstation ownership reset/fix
-        echo "uid=$(id -u ${USER})" >> $GITHUB_OUTPUT
-    - uses: peter-murray/reset-workspace-ownership-action@v1
-      if: steps.diff.outputs.triggered == 'true'
-      with:
-        user_id: ${{ steps.get_uid.outputs.uid }}
+        echo "Triggered: ${{ steps.diff.outputs.triggered }}"
 
-    # Fix - Clone for action.yml and other verifications
-    - name: Checkout Action repo to pass tests
-      if: always() && inputs.repository != github.repository
-      uses: actions/checkout@v4
+    # # Setup Java and cache dir
+    # - uses: actions/setup-java@v4
+    #   with:
+    #     cache: ${{ inputs.java-cache }}
+    #     distribution: ${{ inputs.java-distribution }}
+    #     java-version: ${{ inputs.java-version }}
+    #     server-id: 'github'
+
+    # # Run tests, hopefully generating coverage for SonarCloud
+    # - name: Run Tests
+    #   if: steps.diff.outputs.triggered == 'true'
+    #   shell: bash
+    #   run: |
+    #     # Run tests
+    #     cd ${{ inputs.dir }}
+    #     ${{ inputs.commands }}
+
+    # ### Optional SonarCloud
+
+    # - if: inputs.sonar_token && steps.diff.outputs.triggered == 'true'
+    #   env:
+    #     SONAR_TOKEN: ${{ inputs.sonar_token }}
+    #   shell: bash
+    #   run: |
+    #     # Run SonarCloud for ${{ inputs.java-cache }}
+
+    #     if [ "${{ inputs.java-cache }}" == "maven" ]; then
+    #       SONAR_CMD="mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar"
+    #     elif [ "${{ inputs.java-cache }}" == "gradle" ]; then
+    #       SONAR_CMD="./gradlew build sonarqube --info"
+    #     else
+    #       echo "ERROR: inputs.java-cache = ${{ inputs.java-cache }}"
+    #       exit 1
+    #     fi
+
+    #     cd ${{ inputs.dir }}
+    #     "${SONAR_CMD}" -Dsonar.host.url=https://sonarcloud.io ${{ inputs.sonar_args }}
+
+    # ### Cleanup
+
+    # # Fix - Docker can take file ownership, causing a cleanup fail
+    # - shell: bash
+    #   if: steps.diff.outputs.triggered == 'true'
+    #   id: get_uid
+    #   run: |
+    #     # User for workstation ownership reset/fix
+    #     echo "uid=$(id -u ${USER})" >> $GITHUB_OUTPUT
+    # - uses: peter-murray/reset-workspace-ownership-action@v1
+    #   if: steps.diff.outputs.triggered == 'true'
+    #   with:
+    #     user_id: ${{ steps.get_uid.outputs.uid }}
+
+    # # Fix - Clone for action.yml and other verifications
+    # - name: Checkout Action repo to pass tests
+    #   if: always() && inputs.repository != github.repository
+    #   uses: actions/checkout@v4
