Cleanup

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -112,17 +112,14 @@ runs:
       run: |
         # Run SonarCloud for ${{ inputs.java-cache }}
 
-        # if [ "${{ inputs.java-cache }}" == "maven" ]; then
-        #   SONAR_CMD="mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar"
-        # elif [ "${{ inputs.java-cache }}" == "gradle" ]; then
-        #   SONAR_CMD="./gradlew build sonarqube --info"
-        # else
-        #   echo "ERROR: inputs.java-cache = ${{ inputs.java-cache }}"
-        #   exit 1
-        # fi
-
-        # "${SONAR_CMD}" -Dsonar.host.url=https://sonarcloud.io ${{ inputs.sonar_args }}
-        mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.host.url=https://sonarcloud.io ${{ inputs.sonar_args }}
+        if [ "${{ inputs.java-cache }}" == "maven" ]; then
+          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.host.url=https://sonarcloud.io ${{ inputs.sonar_args }}
+        elif [ "${{ inputs.java-cache }}" == "gradle" ]; then
+          gradlew build sonarqube --info -Dsonar.host.url=https://sonarcloud.io ${{ inputs.sonar_args }}
+        else
+          echo "ERROR: inputs.java-cache = ${{ inputs.java-cache }}"
+          exit 1
+        fi
 
     ### Cleanup
 
